### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by anderbytes** [OpenMediaVault-Plugin-Developers/openmediavault-apttool#2]
Congratulations for the great idea for a plugin.

Apart from the Pull request that I suggested, I want to give some other ideas for it:
1. Put "Packages" tab as the Home of the plugin, not Search. It is nice to Enter plugin and already see useful information (current packages), instead of directly to a Search.

2. In the Search resulsts, make it possible that a double-click try to install that package, unless it is already installed (then show a message)

3.a. In the Packages grid, create another column for actions (Install, Remove), and show whether the package is Installed or not at the time
3.b Instead than suggested above, there could be separated grids for Installed or Non-Installed Packages. A nice parallel view, just like seen in Docker (Images on one grid, Containers in other)

What do you think?

**Comment by ryecoaaron** [comment]
Thanks.  Just made the plugin for my development VMs.  Didn't know if anyone else would find it useful or not :)
1 - Ok.
2 - Probably can't be double click but I could add an Install button along with the other buttons?
3a - I don't think that should be hard to do.  Will have to check how fast it is with a couple pages of entries.
3b - I can look into that but if the current grid had a column for installed status, the packages could be sorted by that status.  Would that be enough?

**Comment by anderbytes** [comment]
It is very useful, yes! Usually OMV users at some point have to manually install extra packages via APT. As OMV should be purely a NAS server, those extra packages really have to be VERY carefully managed. Your plugin does this very well, keeping track of packages.

2. A Install button could be useful. But it should be avoided to reinstall a same package that already exists (in this case, Install button could be Grayed). And where would it be? At right of each line? At right of "Search Local", after a vertical Separator?

3.a. Allright. thanks.
3.b. If sortable, yes, that would be very enough.

Thanks for the quick answer! I don't have much programming skills, then I can help testing and with suggestions.

**Comment by ryecoaaron** [comment]
2 - The install button would be to the right of the Search Local button.  Even if you did install an installed package again, it wouldn't hurt anything.

**Comment by anderbytes** [comment]
Allright. Good job on the plugin!

**Comment by ryecoaaron** [comment]
3.3 is in the repo.  Instead of installing from the search tab, it adds the package to the packages tab.  You can install from there.

**Comment by anderbytes** [comment]
Thank you! I've tested it and there's something to be fixed :  when I click "add to Packages tab", it doesn't give me any feedback, and the new package doesn't appear automatically at the packages list.

So I toughout my "add" didn't happened and tried again. Then appeared the error "**_The configuration object 'conf.service.apttool.package' is not unique. An object with the property 'packagename' and value 'mediainfo' already exists._**" because it was already there before, and I had to reload the page to make it appear.

Also... trying to add a package that already exists throws an untreated error (same text as above). It's easily reproduceable.

**Comment by anderbytes** [comment]
One more: when we click "Search Local", make "Add to Packages" become Grayed

**Comment by ryecoaaron** [comment]
You don't have to refresh the page.  You just need to click the refresh button on the bottom left of the grid.  I could make the grid autorefresh but that gets annoying.  The error is correct.  It doesn't let you add a package more than once whether you add it from the packages tab or the search tab.  It isn't an error in the code.  That is just how OMV tells you that you are adding a duplicate.

The Add to Packages button becomes disabled when no item in the grid is selected or when more than one item in the grid is selected.  The Add to Packages button does not work when you use search local though.  There is code to tell you that you have to search the repositiories.

**Comment by anderbytes** [comment]
Everything's okay. I was just pointing out  :-)

Good work there.
