### ISSUE TITLE
some errors i came across on OMV5

### ISSUE THREAD

**Issue by coffinbearer** [OpenMediaVault-Plugin-Developers/openmediavault-apttool#3]
First of all thank you for your work on the invaluable omv-extras. today i played a litte with omv5 an came across a few errors.

apttool tries to use jessie-backports:
Error:
E: The value ‘jessie-backports’ is invalid for APT::Default-Release as such a release is not available in the sources
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-apttool/blob/12c200bd5a941c7da4caaa3827aadd812529c034/usr/share/openmediavault/engined/rpc/apttool.inc#L206-L207

foce-yes is deprecated :
Error:
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Source:
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-apttool/blob/12c200bd5a941c7da4caaa3827aadd812529c034/usr/share/openmediavault/engined/rpc/apttool.inc#L209

**Comment by ryecoaaron** [comment]
Fixed in 3.6 - 186dbdfce12554e7aff40e9e4355eefde85e52ef
